rom django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

def validate_answer():
	return True